component.o: component.cpp component.h
io.o: io.cpp io.h component.h
random.o: random.cpp random.h component.h
andgate.o: andgate.cpp andgate.h component.h
orgate.o: orgate.cpp orgate.h component.h
xorgate.o: xorgate.cpp xorgate.h component.h
nandgate.o: nandgate.cpp nandgate.h component.h
complement.o: complement.cpp complement.h component.h
test.o: test.cpp components.h io.h component.h complement.h random.h \
  andgate.h orgate.h
