aescipher.o: aescipher.cpp FileSource.h CryptoFileSource.h
FileSource.o: FileSource.cpp FileSource.h
CryptoFileSource.o: CryptoFileSource.cpp CryptoFileSource.h
dataplot.o: dataplot.cpp dataplot.h
MMAP.o: MMAP.cpp MMAP.h
mapping.o: mapping.cpp MMAP.h
nntool.o: nntool.cpp argparser.tab.h cpuid_threads.h
argparser.tab.o: argparser.tab.cpp nntool.h
cpuid_threads.o: cpuid_threads.cpp cpuid_threads.h
datatool.o: datatool.cpp
gendata.o: gendata.cpp
